/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author cocotle
 */
public class GUI_Tripulante extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Tripulante
     */
    public GUI_Tripulante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttnGroup_sexo = new javax.swing.ButtonGroup();
        bttnGroup_tripulante = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_edad = new javax.swing.JTextField();
        txt_carnet = new javax.swing.JTextField();
        txt_tiempoEmpresa = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        radioBttn_hombre = new javax.swing.JRadioButton();
        radioBttn_mujer = new javax.swing.JRadioButton();
        combo_barco = new javax.swing.JComboBox<>();
        radioBttn_capitan = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        radioBttn_jefe = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        radioBttn_marinero = new javax.swing.JRadioButton();
        bttn_limpiar = new javax.swing.JButton();
        bttn_agregar = new javax.swing.JButton();
        txt_capitanExp = new javax.swing.JTextField();
        txt_jefePescado = new javax.swing.JTextField();
        txt_jefeMarisco = new javax.swing.JTextField();
        txt_marineroPescado = new javax.swing.JTextField();

        jLabel1.setText("Agrega la información del tripulante requerido:");

        jLabel2.setText("Datos generales:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Edad:");

        jLabel5.setText("Número de carnet:");

        jLabel6.setText("Tiempo en la empresa:");

        jLabel7.setText("Teléfono:");

        jLabel8.setText("Sexo:");

        jLabel9.setText("Barco asignado:");

        jLabel10.setText("Tipo de tripulante:");

        bttnGroup_sexo.add(radioBttn_hombre);
        radioBttn_hombre.setText("Hombre");
        radioBttn_hombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBttn_hombreActionPerformed(evt);
            }
        });

        bttnGroup_sexo.add(radioBttn_mujer);
        radioBttn_mujer.setText("Mujer");
        radioBttn_mujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBttn_mujerActionPerformed(evt);
            }
        });

        combo_barco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bttnGroup_tripulante.add(radioBttn_capitan);
        radioBttn_capitan.setText("Capitán:");
        radioBttn_capitan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBttn_capitanActionPerformed(evt);
            }
        });

        jLabel11.setText("Horas de experticia:");

        bttnGroup_tripulante.add(radioBttn_jefe);
        radioBttn_jefe.setText("Jefe de flota:");
        radioBttn_jefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBttn_jefeActionPerformed(evt);
            }
        });

        jLabel12.setText("Peso de pescado:");

        jLabel13.setText("Peso de marisco:");

        jLabel14.setText("Peso total de pescado:");

        bttnGroup_tripulante.add(radioBttn_marinero);
        radioBttn_marinero.setText("Marinero:");
        radioBttn_marinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBttn_marineroActionPerformed(evt);
            }
        });

        bttn_limpiar.setText("Limpiar campos");
        bttn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_limpiarActionPerformed(evt);
            }
        });

        bttn_agregar.setText("Agregar tripulante");

        txt_capitanExp.setEnabled(false);

        txt_jefePescado.setEnabled(false);

        txt_jefeMarisco.setEnabled(false);

        txt_marineroPescado.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(radioBttn_jefe)
                            .addComponent(radioBttn_capitan)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14)
                                    .addComponent(bttn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bttn_agregar)
                                .addGap(0, 27, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(radioBttn_mujer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioBttn_hombre))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_marineroPescado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                .addComponent(txt_jefeMarisco, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_capitanExp, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_jefePescado, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel7))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(57, 57, 57)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(91, 91, 91)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_carnet)
                            .addComponent(txt_tiempoEmpresa)
                            .addComponent(txt_telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txt_edad, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10)
                            .addComponent(radioBttn_marinero))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(combo_barco, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_carnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_tiempoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(radioBttn_hombre)
                    .addComponent(radioBttn_mujer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(combo_barco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBttn_capitan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_capitanExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBttn_jefe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_jefePescado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_jefeMarisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBttn_marinero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_marineroPescado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttn_limpiar)
                    .addComponent(bttn_agregar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioBttn_mujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBttn_mujerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBttn_mujerActionPerformed

    private void radioBttn_capitanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBttn_capitanActionPerformed
        txt_capitanExp.setEnabled(true);
        
        txt_jefePescado.setEnabled(false);
        txt_jefeMarisco.setEnabled(false);
        txt_marineroPescado.setEnabled(false);
        
        txt_jefePescado.setText("");
        txt_jefeMarisco.setText("");
        txt_marineroPescado.setText("");
    }//GEN-LAST:event_radioBttn_capitanActionPerformed

    private void radioBttn_jefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBttn_jefeActionPerformed
        txt_jefePescado.setEnabled(true);
        txt_jefeMarisco.setEnabled(true);
        
        txt_capitanExp.setEnabled(false);
        txt_marineroPescado.setEnabled(false);
        
        txt_capitanExp.setText("");
        txt_marineroPescado.setText("");
    }//GEN-LAST:event_radioBttn_jefeActionPerformed

    private void radioBttn_marineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBttn_marineroActionPerformed
        txt_marineroPescado.setEnabled(true);
        
        txt_capitanExp.setEnabled(false);
        txt_jefePescado.setEnabled(false);
        txt_jefeMarisco.setEnabled(false);
        
        txt_capitanExp.setText("");
        txt_jefePescado.setText("");
        txt_jefeMarisco.setText("");
    }//GEN-LAST:event_radioBttn_marineroActionPerformed

    private void radioBttn_hombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBttn_hombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBttn_hombreActionPerformed

    private void bttn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_limpiarActionPerformed
        txt_nombre.setText("");
        txt_edad.setText("");
        txt_carnet.setText("");
        txt_tiempoEmpresa.setText("");
        txt_telefono.setText("");
        txt_capitanExp.setText("");
        txt_jefePescado.setText("");
        txt_jefeMarisco.setText("");
        txt_marineroPescado.setText("");
    }//GEN-LAST:event_bttn_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Tripulante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Tripulante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Tripulante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Tripulante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Tripulante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bttnGroup_sexo;
    private javax.swing.ButtonGroup bttnGroup_tripulante;
    private javax.swing.JButton bttn_agregar;
    private javax.swing.JButton bttn_limpiar;
    private javax.swing.JComboBox<String> combo_barco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton radioBttn_capitan;
    private javax.swing.JRadioButton radioBttn_hombre;
    private javax.swing.JRadioButton radioBttn_jefe;
    private javax.swing.JRadioButton radioBttn_marinero;
    private javax.swing.JRadioButton radioBttn_mujer;
    private javax.swing.JTextField txt_capitanExp;
    private javax.swing.JTextField txt_carnet;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextField txt_jefeMarisco;
    private javax.swing.JTextField txt_jefePescado;
    private javax.swing.JTextField txt_marineroPescado;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_tiempoEmpresa;
    // End of variables declaration//GEN-END:variables
}
